EVALUATOR_VERSION = "phase_7_evaluator_v0.1"

VERDICT_SAFE = "safe"
VERDICT_SUSPICIOUS = "suspicious"
VERDICT_VULNERABLE = "vulnerable"
VERDICT_NEEDS_MANUAL_REVIEW = "needs_manual_review"
VERDICT_INCONCLUSIVE = "inconclusive"
VERDICT_ERROR = "error"

ALLOWED_VERDICTS = (
    VERDICT_SAFE,
    VERDICT_SUSPICIOUS,
    VERDICT_VULNERABLE,
    VERDICT_NEEDS_MANUAL_REVIEW,
    VERDICT_INCONCLUSIVE,
    VERDICT_ERROR,
)

SEVERITY_CRITICAL = "critical"
SEVERITY_HIGH = "high"
SEVERITY_MEDIUM = "medium"
SEVERITY_LOW = "low"
SEVERITY_INFORMATIONAL = "informational"
SEVERITY_NONE = "none"

ALLOWED_SEVERITIES = (
    SEVERITY_CRITICAL,
    SEVERITY_HIGH,
    SEVERITY_MEDIUM,
    SEVERITY_LOW,
    SEVERITY_INFORMATIONAL,
    SEVERITY_NONE,
)

CONFIDENCE_HIGH = "high"
CONFIDENCE_MEDIUM = "medium"
CONFIDENCE_LOW = "low"
CONFIDENCE_NONE = "none"

ALLOWED_CONFIDENCES = (
    CONFIDENCE_HIGH,
    CONFIDENCE_MEDIUM,
    CONFIDENCE_LOW,
    CONFIDENCE_NONE,
)

SEVERITY_RANK = {
    SEVERITY_NONE: 0,
    SEVERITY_INFORMATIONAL: 1,
    SEVERITY_LOW: 2,
    SEVERITY_MEDIUM: 3,
    SEVERITY_HIGH: 4,
    SEVERITY_CRITICAL: 5,
}

CONFIDENCE_RANK = {
    CONFIDENCE_NONE: 0,
    CONFIDENCE_LOW: 1,
    CONFIDENCE_MEDIUM: 2,
    CONFIDENCE_HIGH: 3,
}

SIGNAL_CANARY_TOKEN = "canary_token_leakage"
SIGNAL_SENSITIVE_DATA = "sensitive_data_pattern"
SIGNAL_SYSTEM_PROMPT = "system_prompt_leakage"
SIGNAL_UNSAFE_OUTPUT = "unsafe_output"
SIGNAL_TOOL_ABUSE = "tool_function_abuse"
SIGNAL_COST_ABUSE = "cost_abuse"
SIGNAL_FAILURE_SIGNAL = "prompt_library_failure_signal"
SIGNAL_MANUAL_REVIEW = "manual_review_trigger"
